version: "3.9"

services:
  sqlserver:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password12345!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - saillinglocnetwork
    restart: unless-stopped
    # Healthcheck simple (test TCP) – pas besoin de sqlcmd
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1433' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 20s

  saillingloc:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8095:8080"   # HTTP
      - "8096:8443"   # HTTPS si tu l’actives
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      # Connection string pour l’API **dans le réseau Docker**
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=SaillingLoc2;User Id=sa;Password=Password12345!;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - saillinglocnetwork

networks:
  saillinglocnetwork:

volumes:
  sqlvolume:
