services:
  sqlserverDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        MSSQL_SA_PASSWORD: "Password12345!"
        ACCEPT_EULA: "Y"
    ports:
        -   "1433:1433"
    volumes:
        - "sqlvolume:/var/opt/mssql"
    networks:
        - saillinglocnetwork
    restart: unless-stopped

  saillingloc:
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
        - "8095:8080"
        - "8096:8081"  #Cette ligne represente pour le HTTPS
    depends_on:
        -   sqlserverDb
    networks:
        -   saillinglocnetwork
networks:
    saillinglocnetwork:
volumes:
    sqlvolume:    
        